=== AbdorrahmanRamadan/ITI-OpenSource-9-Months-Training/XML/Lab 2 XML/Employees.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT Employees (Employee)*>
<!ELEMENT Employee (name,phones,adresses,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone)+>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>
<!ELEMENT adresses (adress)+>
<!ELEMENT adress (street,buildingNumber,region,city,country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT buildingNumber (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== AbdorrahmanRamadan/ITI-OpenSource-9-Months-Training/XML/Lab 2 XML/Employees.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="Employees.css"?>
<!DOCTYPE Employees SYSTEM "Employees.dtd">
<Employees xmlns:xsd = "http://www.w3.org/2001/XMLSchema-instance"  xsd:noNamespaceSchemaLocation ="Employees.xsd">
	<Employee>
		<name>Abdo</name>
		<phones>
			<phone type="mobile">123456789</phone>
			<phone type="work">123456789</phone>
			<phone type="home">123456789</phone>
		</phones>
		<adresses>
			<adress>
				<street>1</street>
				<buildingNumber>12</buildingNumber>
				<region>region</region>
				<city>city name</city>
				<country>country name</country>
			</adress>
			<adress>
				<street>1</street>
				<buildingNumber>14</buildingNumber>
				<region>region</region>
				<city>city name</city>
				<country>country name</country>
			</adress>
		</adresses>
		<email>Sample@Sample.com</email>
	</Employee>
	<Employee>
		<name>Ahmed</name>
		<phones>
			<phone type="mobile">123456789</phone>
			<phone type="work">123456789</phone>
			<phone type="home">123456789</phone>
		</phones>
		<adresses>
			<adress>
				<street>2</street>
				<buildingNumber>24</buildingNumber>
				<region>region</region>
				<city>city name</city>
				<country>country name</country>
			</adress>
		</adresses>
		<email>Sample@Sample.com</email>
	</Employee>
	<Employee>
		<name>Ali</name>
		<phones>
			<phone type="mobile">123456789</phone>
			<phone type="work">123456789</phone>
			<phone type="home">123456789</phone>
		</phones>
		<adresses>
			<adress>
				<street>2</street>
				<buildingNumber>2</buildingNumber>
				<region>region</region>
				<city>city name</city>
				<country>country name</country>
			</adress>
		</adresses>
		<email>Sample@Sample.com</email>
	</Employee>
</Employees>
